_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "10":
                - 20
            "12": 0.19.9
            "13": windows-amd64
hidden_dim:
    value: 256
input_dim:
    value: 50
learning_rate:
    value: 0.001
model_name:
    value: MLP
num_epochs:
    value: 10
